# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
default: &defaults
  docker:
        # specify the version you desire here
        - image: circleci/android:api-24-alpha
        
        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/postgres:9.4

      working_directory: ~/repo
      environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

version: 2
jobs:
   android_lint:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Running static analysis tools
      - run:
          name: Running quality checks
          command: |
            echo "Run android lint"
            cd ~/repo
            ./gradlew lint

      # Storing reports
      - store_artifacts:
          path: ~/repo/app/build/reports

      # Sending notification
      - run:
          name: Notifying slack channel (succeeded)
          when: on_success
          command: |
            bash ~/repo/.circleci/notify_slack.sh
      - run:
          name: Notifying slack channel (failed)
          when: on_fail
          command: |
            bash ~/repo/.circleci/notify_slack_fail.sh
      

   findbugs_lint:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Running static analysis tools
      - run:
          name: Running quality checks
          command: |
            echo "Run findbugs"
            cd ~/repo
            ./gradlew assemble
            ./gradlew findbugs

      # Storing reports
      - store_artifacts:
          path: ~/repo/app/build/outputs

      # Sending notification
      - run:
          name: Notifying slack channel (succeeded)
          when: on_success
          command: |
            bash ~/repo/.circleci/notify_slack.sh
      - run:
          name: Notifying slack channel (failed)
          when: on_fail
          command: |
            bash ~/repo/.circleci/notify_slack_fail.sh   
      
   pmd_lint:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Running static analysis tools
      - run:
          name: Running quality checks
          command: |
            echo "Run PMD"
            cd ~/repo
            ./gradlew pmd

      # Storing reports
      - store_artifacts:
          path: ~/repo/app/build

      # Sending notification
      - run:
          name: Notifying slack channel (succeeded)
          when: on_success
          command: |
            bash ~/repo/.circleci/notify_slack.sh
      - run:
          name: Notifying slack channel (failed)
          when: on_fail
          command: |
            bash ~/repo/.circleci/notify_slack_fail.sh

  checkstyle_lint:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Running static analysis tools
      - run:
          name: Running quality checks
          command: |
            echo "Run checkstyle"
            cd ~/repo
            ./gradlew checkstyle

      # Storing reports
      - store_artifacts:
          path: ~/repo/app/build/reports

      # Sending notification
      - run:
          name: Notifying slack channel (succeeded)
          when: on_success
          command: |
            bash ~/repo/.circleci/notify_slack.sh
      - run:
          name: Notifying slack channel (failed)
          when: on_fail
          command: |
            bash ~/repo/.circleci/notify_slack_fail.sh   
      
      
      # run tests!
      - run: ./gradlew test




